version: '3.8'

services:
  db:
    image: mysql:8.0
    container_name: miniweb-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: myflaskapp
      MYSQL_USER: miniweb_user
      MYSQL_PASSWORD: miniweb_pass
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-proot"]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    build:
      context: .
      dockerfile: users/backend/Dockerfile
    container_name: miniweb-backend
    restart: always
    environment:
      FLASK_ENV: production
      DATABASE_URL: "mysql+pymysql://miniweb_user:miniweb_pass@db:3306/myflaskapp"
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "5001:8000"
    volumes:
      - .:/app

  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: miniweb-frontend
    restart: always
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - backend
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - .:/app

volumes:
  db_data:
